mutation CreateNewUser($username: String!, $email: String!) @auth(level: USER) {
  user_insert(data: {username: $username, email: $email, createdAt_expr: "request.time"})
}

query GetTopic @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  topics {
    id
    name
    description
  }
}

mutation SaveProblemForUser($problemId: UUID!, $notes: String) @auth(level: USER) {
  savedProblem_insert(data: {
    problemId: $problemId,
    userId_expr: "auth.uid",
    notes: $notes,
    savedAt_expr: "request.time"
  })
}

query GetUserProgressForTopic(@auth(level: USER) {
  userProgress(key: {userId_expr: "auth.uid", topicId: $topicId}) {
    isCompleted
    score
  }
}